name: readit
description: A new Flutter project.
version: 1.1.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.7
  flutter_icons: ^1.0.0+1
  path_provider: ^1.6.0
  path_provider_macos: ^0.0.4
  http: ^0.12.0+4
  objectdb: ^1.0.7+1
  cached_network_image: ^2.0.0
  uuid: ^2.0.4
  url_launcher: ^5.4.1
  shimmer: ^1.1.0
  url_launcher_macos: ^0.0.1+4
  validators: ^2.0.0+1
  flutter_html: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter:
  uses-material-design: true

flutter_icons:
  image_path: assets/icon.png
  android: true
  ios: true
